package com.bailout.stick.new_electronic_by_Rodeon.ui.activities.helps


enum class TypeGuides {
    SHOW_HELP_GUIDE,
    SHOW_DEVICE_NAME_GUIDE,
    SHOW_VERSION_GUIDE,
    SHOW_MOVEMENT_BUTTONS_GUIDE,
    SHOW_SENSORS_SENSITIVITY_GUIDE,
    SHOW_SENSORS_THRESHOLD_LEVELS_GUIDE,
    SHOW_OPEN_SENSORS_THRESHOLD_AREA_GUIDE,
    SHOW_CLOSE_SENSORS_THRESHOLD_AREA_GUIDE,
    SHOW_SENSORS_SWAP_GUIDE,
    SHOW_SENSORS_SENSITIVITY_CLARIFICATION_GUIDE,
    SHOW_BLOCKING_GUIDE,
    END_GUIDE
}