package com.bailout.stickk.ubi4.versions.v3.domain.settings

/** Stable setting identifiers; the data layer maps them to the existing protocol registry. */
object V3ParameterKeys {
    const val P_KEY_DEVICE_ROLE = "P_KEY_DEVICE_ROLE"
    const val P_KEY_EMG_CHANGE_GESTURE = "P_KEY_EMG_CHANGE_GESTURE"
    const val P_KEY_EMG_CONTROL_MODE = "P_KEY_EMG_CONTROL_MODE"
    const val P_KEY_EMG_GAIN_CLOSE_VALUE = "P_KEY_EMG_GAIN_CLOSE_VALUE"
    const val P_KEY_EMG_GAIN_OPEN_VALUE = "P_KEY_EMG_GAIN_OPEN_VALUE"
    const val P_KEY_EMG_MAX_GAIN_VALUE = "P_KEY_EMG_MAX_GAIN_VALUE"
    const val P_KEY_EMG_MOVEMENT_LOCK = "P_KEY_EMG_MOVEMENT_LOCK"
    const val P_KEY_FORCE_SETTINGS = "P_KEY_FORCE_SETTINGS"
    const val P_KEY_GESTURE_CHANGE_MODE = "P_KEY_GESTURE_CHANGE_MODE"
    const val P_KEY_GLOBAL_INDEX_MIDDLE_CLOSED_POSITION = "P_KEY_GLOBAL_INDEX_MIDDLE_CLOSED_POSITION"
    const val P_KEY_GLOBAL_THUMB_CLOSED_POSITION = "P_KEY_GLOBAL_THUMB_CLOSED_POSITION"
    const val P_KEY_HAND_CONTROL_MODE = "P_KEY_HAND_CONTROL_MODE"
    const val P_KEY_LEFT_RIGHT_HAND = "P_KEY_LEFT_RIGHT_HAND"
    const val P_KEY_SCREEN_TIMEOUT = "P_KEY_SCREEN_TIMEOUT"
    const val P_KEY_SETTINGS_PROFILE = "P_KEY_SETTINGS_PROFILE"
    const val P_KEY_SET_DEVICE_NAME = "P_KEY_SET_DEVICE_NAME"
    const val P_KEY_SET_SERIAL_NUMBER = "P_KEY_SET_SERIAL_NUMBER"
    const val P_KEY_SPEED_SETTINGS = "P_KEY_SPEED_SETTINGS"
    const val P_KEY_START_CALIBRATE_COMMAND = "P_KEY_START_CALIBRATE_COMMAND"
}
