package me.start.motorica.new_electronic_by_Rodeon.ui.activities.helps


enum class TypeDimMasks {
    CIRCLE, RECTANGLE, HORISONTAL_RECTANGLE, HORISONTAL_RECTANGLE_ALL_WIDTH, HORISONTAL_RECTANGLE_ALL_WIDTH_MOVEMENT_BUTTONS,  VERTICAL_RECTANGLE
}