package com.bailout.stickk.ubi4.resources

interface ResourceProvider {
    fun getString(id: ResourceString): String
    fun getRaw(id: ResourceRaw): Int
    fun getDrawable(id: ResourceDrawable): Int
}

enum class ResourceString {
    THUMB_FINGER,
    FLEXION,
    EXTENSION,
    PALM_CLOSING,
    PALM_OPENING,
    OK_PINCH,
    PISTOL_POINTER_GESTURE,
    GESTURE_KEY,
    ADDUCTION,
    ABDUCTION,
    PRONATION,
    SUPINATION,
    FIST,
    GESTURE_POINT,
    GESTURE_PINCH,
    GESTURE_FIST_THUMB_OVER,
    GESTURE_ROCK,
    GESTURE_TWIZZERS,
    GESTURE_CUPHOLDER,
    GESTURE_HALF_GRAB,
    GESTURE_OK,
    GESTURE_THUMB_UP,
    GESTURE_MIDDLE_FINGER,
    GESTURE_DOUBLE_POINT,
    GESTURE_CALL_ME,
    GESTURE_NATURAL_POSITION,
    GESTURE_1_BTN,
    GESTURE_2_BTN,
    GESTURE_3_BTN,
    GESTURE_4_BTN,
    GESTURE_5_BTN,
    GESTURE_6_BTN,
    GESTURE_7_BTN,
    GESTURE_8_BTN,
    GESTURE_9_BTN,
    GESTURE_10_BTN,
    GESTURE_11_BTN,
    GESTURE_12_BTN,
    GESTURE_13_BTN,
    GESTURE_14_BTN
}

enum class ResourceRaw {
    THUMB_FINGERS,
    WRIST_FLEX,
    WRIST_EXTEND,
    CLOSE,
    OPEN,
    PINCH,
    INDICATION,
    KEY,
    ADDUCTION,
    ABDUCTION,
    PRONATION,
    SUPINATION
}
enum class ResourceDrawable {
    COLLECTION_FIST_1,
    COLLECTION_POINT,
    COLLECTION_PINCH,
    COLLECTION_FIST_2,
    COLLECTION_KEY,
    COLLECTION_ROCK,
    COLLECTION_TWIZZERS,
    COLLECTION_CUPHOLDER,
    COLLECT_HALF_GRAB,
    COLLECTION_OK,
    COLLECTION_THUMB_UP,
    COLLECTION_MIDDLE_FINGER,
    COLLECTION_DOUBLE_POINT,
    COLLECTION_CALL_ME,
    COLLECTION_NATURAL_POSITION
}
